[package]
name = "systemd-gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.7", package = "libadwaita", features = ["v1_6"] }
async-channel = "2.3.1"
gtk = { version = "0.9", package = "gtk4", features = ["gnome_47"] }
systemctl = "0.4"

[build-dependencies]
glib-build-tools = "0.20.0"
